# used to initialize volume mounted dev environment
# run with
#  'sudo docker build -t grpc --file Dockerfile.dev .'
#  'sudo docker run --volume "$(pwd)":/go/src/github.com/GeorgeLuo/grpc --interactive --tty --publish 8443:8443 grpc'

FROM golang

ADD . /go/src/github.com/GeorgeLuo/grpc

# Install deps
RUN go get github.com/gorilla/mux
RUN go get github.com/olekukonko/tablewriter

WORKDIR /go/src/github.com/GeorgeLuo/grpc

# Set default run command
CMD ["bash"]

# Expose port 8443.
EXPOSE 8443
